### ISSUE TITLE
update spotinst-ocean-controller image to 1.0.37

### ISSUE THREAD

**Issue by somebody-nobody** [spotinst/terraform-spotinst-modules#7]
Hello, 

currently spotinst-ocean-controller is using `1.0.30` of the image: https://github.com/spotinst/terraform-spotinst-modules/blob/master/spotinst_ocean_controller/main.tf#L132

Could you please update it to the latest `1.0.37`?

Thanks a lot!

**Comment by Artemu** [comment]
Just had the same issue myself, pushed a PR to make the versioning dynamic. https://github.com/spotinst/terraform-spotinst-modules/pull/8
